// foodDatabase.js — FitAI Complete Food Database (200+ foods)
const FOOD_DB = {

  // ══════════════════════════════════════
  // 🟢 SOUTH INDIAN
  // ══════════════════════════════════════
  'idli':               { cal: 39,  p: 2,   c: 8,   f: 0.2, unit: 'piece' },
  'dosa':               { cal: 120, p: 3,   c: 20,  f: 3,   unit: 'piece' },
  'masala dosa':        { cal: 215, p: 5,   c: 32,  f: 7,   unit: 'piece' },
  'rava dosa':          { cal: 150, p: 4,   c: 22,  f: 5,   unit: 'piece' },
  'set dosa':           { cal: 110, p: 3,   c: 18,  f: 3,   unit: 'piece' },
  'sambar':             { cal: 50,  p: 3,   c: 8,   f: 1,   unit: '100ml' },
  'chutney':            { cal: 45,  p: 1,   c: 5,   f: 2,   unit: 'tbsp' },
  'coconut chutney':    { cal: 60,  p: 1,   c: 4,   f: 5,   unit: 'tbsp' },
  'vada':               { cal: 97,  p: 3,   c: 12,  f: 4,   unit: 'piece' },
  'medu vada':          { cal: 97,  p: 3,   c: 12,  f: 4,   unit: 'piece' },
  'upma':               { cal: 150, p: 4,   c: 25,  f: 4,   unit: 'cup' },
  'rava upma':          { cal: 150, p: 4,   c: 25,  f: 4,   unit: 'cup' },
  'pongal':             { cal: 180, p: 5,   c: 30,  f: 5,   unit: 'cup' },
  'ven pongal':         { cal: 180, p: 5,   c: 30,  f: 5,   unit: 'cup' },
  'rasam':              { cal: 30,  p: 1,   c: 5,   f: 0.5, unit: '100ml' },
  'rice':               { cal: 130, p: 3,   c: 28,  f: 0.3, unit: 'cup' },
  'white rice':         { cal: 130, p: 3,   c: 28,  f: 0.3, unit: 'cup' },
  'brown rice':         { cal: 112, p: 2.6, c: 24,  f: 0.9, unit: 'cup' },
  'biryani':            { cal: 290, p: 12,  c: 40,  f: 8,   unit: 'cup' },
  'chicken biryani':    { cal: 320, p: 18,  c: 38,  f: 10,  unit: 'cup' },
  'veg biryani':        { cal: 250, p: 6,   c: 42,  f: 6,   unit: 'cup' },
  'parotta':            { cal: 260, p: 5,   c: 38,  f: 10,  unit: 'piece' },
  'poori':              { cal: 110, p: 2,   c: 14,  f: 5,   unit: 'piece' },
  'puri':               { cal: 110, p: 2,   c: 14,  f: 5,   unit: 'piece' },
  'appam':              { cal: 80,  p: 2,   c: 16,  f: 1,   unit: 'piece' },
  'idiyappam':          { cal: 90,  p: 2,   c: 19,  f: 0.5, unit: 'piece' },
  'puttu':              { cal: 100, p: 2,   c: 22,  f: 0.5, unit: '100g' },
  'pesarattu':          { cal: 95,  p: 5,   c: 15,  f: 2,   unit: 'piece' },
  'uttapam':            { cal: 130, p: 4,   c: 22,  f: 3,   unit: 'piece' },
  'poha':               { cal: 158, p: 3,   c: 32,  f: 2,   unit: 'cup' },
  'fried rice':         { cal: 250, p: 8,   c: 40,  f: 7,   unit: 'cup' },
  'egg fried rice':     { cal: 290, p: 12,  c: 38,  f: 9,   unit: 'cup' },
  'lemon rice':         { cal: 160, p: 3,   c: 30,  f: 4,   unit: 'cup' },
  'curd rice':          { cal: 150, p: 5,   c: 27,  f: 3,   unit: 'cup' },
  'tamarind rice':      { cal: 180, p: 3,   c: 34,  f: 4,   unit: 'cup' },
  'payasam':            { cal: 180, p: 4,   c: 30,  f: 5,   unit: 'cup' },
  'halwa':              { cal: 200, p: 3,   c: 30,  f: 8,   unit: '100g' },
  'ladoo':              { cal: 175, p: 3,   c: 25,  f: 7,   unit: 'piece' },
  'murukku':            { cal: 150, p: 3,   c: 20,  f: 6,   unit: '30g' },
  'mixture':            { cal: 140, p: 3,   c: 18,  f: 7,   unit: '30g' },

  // ══════════════════════════════════════
  // 🟡 NORTH INDIAN
  // ══════════════════════════════════════
  'chapati':            { cal: 70,  p: 3,   c: 13,  f: 1,   unit: 'piece' },
  'roti':               { cal: 70,  p: 3,   c: 13,  f: 1,   unit: 'piece' },
  'naan':               { cal: 262, p: 9,   c: 45,  f: 5,   unit: 'piece' },
  'paratha':            { cal: 180, p: 4,   c: 24,  f: 7,   unit: 'piece' },
  'aloo paratha':       { cal: 220, p: 5,   c: 30,  f: 9,   unit: 'piece' },
  'dal':                { cal: 115, p: 9,   c: 20,  f: 1,   unit: 'cup' },
  'dal tadka':          { cal: 130, p: 9,   c: 18,  f: 4,   unit: 'cup' },
  'dal makhani':        { cal: 180, p: 10,  c: 20,  f: 7,   unit: 'cup' },
  'rajma':              { cal: 127, p: 9,   c: 22,  f: 0.5, unit: 'cup' },
  'chole':              { cal: 150, p: 8,   c: 25,  f: 3,   unit: 'cup' },
  'paneer':             { cal: 265, p: 18,  c: 3,   f: 20,  unit: '100g' },
  'paneer butter masala':{ cal: 280, p: 12, c: 15,  f: 20,  unit: 'cup' },
  'palak paneer':       { cal: 240, p: 14,  c: 10,  f: 17,  unit: 'cup' },
  'butter chicken':     { cal: 290, p: 25,  c: 10,  f: 17,  unit: 'cup' },
  'chicken curry':      { cal: 240, p: 22,  c: 8,   f: 14,  unit: 'cup' },
  'mutton curry':       { cal: 280, p: 24,  c: 6,   f: 18,  unit: 'cup' },
  'aloo gobi':          { cal: 150, p: 4,   c: 20,  f: 6,   unit: 'cup' },
  'pav bhaji':          { cal: 300, p: 8,   c: 45,  f: 10,  unit: 'plate' },
  'samosa':             { cal: 130, p: 3,   c: 16,  f: 6,   unit: 'piece' },
  'kachori':            { cal: 180, p: 4,   c: 22,  f: 9,   unit: 'piece' },
  'khichdi':            { cal: 160, p: 6,   c: 28,  f: 3,   unit: 'cup' },
  'pulao':              { cal: 200, p: 5,   c: 35,  f: 5,   unit: 'cup' },
  'kheer':              { cal: 165, p: 5,   c: 28,  f: 4,   unit: 'cup' },
  'gulab jamun':        { cal: 150, p: 2,   c: 25,  f: 5,   unit: 'piece' },
  'jalebi':             { cal: 150, p: 1,   c: 30,  f: 4,   unit: '30g' },
  'raita':              { cal: 60,  p: 3,   c: 6,   f: 2,   unit: 'cup' },

  // ══════════════════════════════════════
  // 🔴 PROTEINS
  // ══════════════════════════════════════
  'egg':                { cal: 78,  p: 6,   c: 0.6, f: 5,   unit: 'piece' },
  'boiled egg':         { cal: 78,  p: 6,   c: 0.6, f: 5,   unit: 'piece' },
  'omelette':           { cal: 154, p: 11,  c: 1,   f: 12,  unit: 'piece' },
  'scrambled egg':      { cal: 140, p: 10,  c: 2,   f: 10,  unit: 'serving' },
  'chicken':            { cal: 165, p: 31,  c: 0,   f: 4,   unit: '100g' },
  'grilled chicken':    { cal: 165, p: 31,  c: 0,   f: 4,   unit: '100g' },
  'fried chicken':      { cal: 250, p: 25,  c: 8,   f: 14,  unit: '100g' },
  'chicken breast':     { cal: 165, p: 31,  c: 0,   f: 4,   unit: '100g' },
  'fish':               { cal: 140, p: 25,  c: 0,   f: 4,   unit: '100g' },
  'salmon':             { cal: 208, p: 20,  c: 0,   f: 13,  unit: '100g' },
  'tuna':               { cal: 130, p: 28,  c: 0,   f: 1,   unit: '100g' },
  'prawn':              { cal: 99,  p: 20,  c: 0,   f: 2,   unit: '100g' },
  'shrimp':             { cal: 99,  p: 20,  c: 0,   f: 2,   unit: '100g' },
  'mutton':             { cal: 250, p: 25,  c: 0,   f: 16,  unit: '100g' },
  'beef':               { cal: 250, p: 26,  c: 0,   f: 15,  unit: '100g' },
  'paneer':             { cal: 265, p: 18,  c: 3,   f: 20,  unit: '100g' },
  'tofu':               { cal: 76,  p: 8,   c: 2,   f: 4,   unit: '100g' },
  'whey protein':       { cal: 130, p: 25,  c: 5,   f: 2,   unit: 'scoop' },
  'protein shake':      { cal: 130, p: 25,  c: 5,   f: 2,   unit: 'scoop' },
  'protein bar':        { cal: 200, p: 20,  c: 20,  f: 6,   unit: 'piece' },

  // ══════════════════════════════════════
  // 🥛 DAIRY
  // ══════════════════════════════════════
  'milk':               { cal: 42,  p: 3.4, c: 5,   f: 1,   unit: '100ml' },
  'full cream milk':    { cal: 61,  p: 3.2, c: 4.8, f: 3.3, unit: '100ml' },
  'curd':               { cal: 60,  p: 3.5, c: 5,   f: 3,   unit: '100g' },
  'yogurt':             { cal: 60,  p: 3.5, c: 5,   f: 3,   unit: '100g' },
  'greek yogurt':       { cal: 100, p: 10,  c: 6,   f: 3,   unit: '100g' },
  'butter':             { cal: 102, p: 0.1, c: 0,   f: 11,  unit: 'tbsp' },
  'ghee':               { cal: 112, p: 0,   c: 0,   f: 12.5,unit: 'tbsp' },
  'cheese':             { cal: 110, p: 7,   c: 0.5, f: 9,   unit: '30g' },
  'paneer':             { cal: 265, p: 18,  c: 3,   f: 20,  unit: '100g' },
  'buttermilk':         { cal: 40,  p: 3,   c: 5,   f: 1,   unit: '200ml' },
  'lassi':              { cal: 120, p: 4,   c: 18,  f: 4,   unit: 'glass' },
  'sweet lassi':        { cal: 180, p: 4,   c: 28,  f: 4,   unit: 'glass' },

  // ══════════════════════════════════════
  // 🍎 FRUITS
  // ══════════════════════════════════════
  'banana':             { cal: 89,  p: 1,   c: 23,  f: 0.3, unit: 'piece' },
  'apple':              { cal: 52,  p: 0.3, c: 14,  f: 0.2, unit: 'piece' },
  'mango':              { cal: 60,  p: 0.8, c: 15,  f: 0.4, unit: '100g' },
  'orange':             { cal: 47,  p: 0.9, c: 12,  f: 0.1, unit: 'piece' },
  'watermelon':         { cal: 30,  p: 0.6, c: 8,   f: 0.2, unit: '100g' },
  'grapes':             { cal: 69,  p: 0.7, c: 18,  f: 0.2, unit: '100g' },
  'papaya':             { cal: 43,  p: 0.5, c: 11,  f: 0.3, unit: '100g' },
  'guava':              { cal: 68,  p: 2.5, c: 14,  f: 1,   unit: '100g' },
  'pomegranate':        { cal: 83,  p: 1.7, c: 19,  f: 1.2, unit: '100g' },
  'pineapple':          { cal: 50,  p: 0.5, c: 13,  f: 0.1, unit: '100g' },
  'strawberry':         { cal: 32,  p: 0.7, c: 8,   f: 0.3, unit: '100g' },
  'kiwi':               { cal: 61,  p: 1.1, c: 15,  f: 0.5, unit: 'piece' },
  'pear':               { cal: 57,  p: 0.4, c: 15,  f: 0.1, unit: 'piece' },
  'coconut':            { cal: 354, p: 3.3, c: 15,  f: 33,  unit: '100g' },

  // ══════════════════════════════════════
  // 🥦 VEGETABLES
  // ══════════════════════════════════════
  'potato':             { cal: 77,  p: 2,   c: 17,  f: 0.1, unit: '100g' },
  'sweet potato':       { cal: 86,  p: 1.6, c: 20,  f: 0.1, unit: '100g' },
  'tomato':             { cal: 18,  p: 0.9, c: 4,   f: 0.2, unit: '100g' },
  'onion':              { cal: 40,  p: 1,   c: 9,   f: 0.1, unit: '100g' },
  'carrot':             { cal: 41,  p: 0.9, c: 10,  f: 0.2, unit: '100g' },
  'spinach':            { cal: 23,  p: 2.9, c: 3.6, f: 0.4, unit: '100g' },
  'broccoli':           { cal: 34,  p: 2.8, c: 7,   f: 0.4, unit: '100g' },
  'cauliflower':        { cal: 25,  p: 2,   c: 5,   f: 0.3, unit: '100g' },
  'cabbage':            { cal: 25,  p: 1.3, c: 6,   f: 0.1, unit: '100g' },
  'corn':               { cal: 86,  p: 3,   c: 19,  f: 1,   unit: '100g' },
  'peas':               { cal: 81,  p: 5,   c: 14,  f: 0.4, unit: '100g' },
  'beans':              { cal: 31,  p: 1.8, c: 7,   f: 0.1, unit: '100g' },
  'cucumber':           { cal: 16,  p: 0.7, c: 4,   f: 0.1, unit: '100g' },
  'mushroom':           { cal: 22,  p: 3,   c: 3,   f: 0.3, unit: '100g' },

  // ══════════════════════════════════════
  // 🍜 CHINESE / FAST FOOD
  // ══════════════════════════════════════
  'noodles':            { cal: 138, p: 4,   c: 25,  f: 2,   unit: 'cup' },
  'hakka noodles':      { cal: 200, p: 6,   c: 32,  f: 6,   unit: 'cup' },
  'chow mein':          { cal: 220, p: 8,   c: 30,  f: 8,   unit: 'cup' },
  'fried rice':         { cal: 250, p: 8,   c: 40,  f: 7,   unit: 'cup' },
  'manchurian':         { cal: 220, p: 8,   c: 25,  f: 10,  unit: 'cup' },
  'spring roll':        { cal: 130, p: 4,   c: 18,  f: 5,   unit: 'piece' },
  'momos':              { cal: 35,  p: 2,   c: 5,   f: 1,   unit: 'piece' },
  'burger':             { cal: 295, p: 15,  c: 35,  f: 10,  unit: 'piece' },
  'pizza':              { cal: 266, p: 11,  c: 33,  f: 10,  unit: 'slice' },
  'sandwich':           { cal: 250, p: 10,  c: 35,  f: 8,   unit: 'piece' },
  'hot dog':            { cal: 290, p: 11,  c: 24,  f: 17,  unit: 'piece' },
  'french fries':       { cal: 312, p: 3.4, c: 41,  f: 15,  unit: '100g' },
  'pasta':              { cal: 158, p: 6,   c: 31,  f: 1,   unit: 'cup' },
  'spaghetti':          { cal: 158, p: 6,   c: 31,  f: 1,   unit: 'cup' },
  'soup':               { cal: 70,  p: 3,   c: 10,  f: 2,   unit: 'bowl' },
  'tomato soup':        { cal: 74,  p: 2,   c: 12,  f: 2,   unit: 'bowl' },
  'corn soup':          { cal: 90,  p: 3,   c: 15,  f: 2,   unit: 'bowl' },

  // ══════════════════════════════════════
  // ☕ DRINKS & BEVERAGES
  // ══════════════════════════════════════
  'tea':                { cal: 30,  p: 0.5, c: 3,   f: 1.5, unit: 'cup' },
  'milk tea':           { cal: 60,  p: 2,   c: 8,   f: 2,   unit: 'cup' },
  'coffee':             { cal: 35,  p: 0.5, c: 3,   f: 2,   unit: 'cup' },
  'black coffee':       { cal: 5,   p: 0.3, c: 0.5, f: 0,   unit: 'cup' },
  'latte':              { cal: 120, p: 6,   c: 12,  f: 5,   unit: 'cup' },
  'cappuccino':         { cal: 80,  p: 4,   c: 8,   f: 3,   unit: 'cup' },
  'juice':              { cal: 45,  p: 0.5, c: 11,  f: 0.2, unit: '100ml' },
  'orange juice':       { cal: 45,  p: 0.7, c: 10,  f: 0.2, unit: '100ml' },
  'mango juice':        { cal: 60,  p: 0.5, c: 15,  f: 0.3, unit: '100ml' },
  'coconut water':      { cal: 19,  p: 0.7, c: 4,   f: 0.2, unit: '100ml' },
  'cold drink':         { cal: 40,  p: 0,   c: 10,  f: 0,   unit: '100ml' },
  'soda':               { cal: 40,  p: 0,   c: 10,  f: 0,   unit: '100ml' },
  'energy drink':       { cal: 45,  p: 0.5, c: 11,  f: 0,   unit: '100ml' },
  'protein shake':      { cal: 130, p: 25,  c: 5,   f: 2,   unit: 'glass' },
  'milkshake':          { cal: 250, p: 7,   c: 38,  f: 8,   unit: 'glass' },
  'smoothie':           { cal: 150, p: 4,   c: 28,  f: 2,   unit: 'glass' },
  'water':              { cal: 0,   p: 0,   c: 0,   f: 0,   unit: 'glass' },

  // ══════════════════════════════════════
  // 🍪 SNACKS & SWEETS
  // ══════════════════════════════════════
  'bread':              { cal: 79,  p: 3,   c: 15,  f: 1,   unit: 'slice' },
  'brown bread':        { cal: 69,  p: 3.5, c: 13,  f: 1,   unit: 'slice' },
  'oats':               { cal: 150, p: 5,   c: 27,  f: 3,   unit: 'cup' },
  'biscuit':            { cal: 50,  p: 0.7, c: 7,   f: 2,   unit: 'piece' },
  'chocolate':          { cal: 155, p: 2,   c: 17,  f: 9,   unit: '30g' },
  'dark chocolate':     { cal: 170, p: 2,   c: 13,  f: 12,  unit: '30g' },
  'ice cream':          { cal: 207, p: 3.5, c: 24,  f: 11,  unit: '100g' },
  'cake':               { cal: 347, p: 5,   c: 53,  f: 13,  unit: '100g' },
  'cookies':            { cal: 150, p: 2,   c: 20,  f: 7,   unit: '30g' },
  'chips':              { cal: 536, p: 7,   c: 53,  f: 35,  unit: '100g' },
  'popcorn':            { cal: 375, p: 11,  c: 74,  f: 4,   unit: '100g' },
  'almonds':            { cal: 164, p: 6,   c: 6,   f: 14,  unit: '28g' },
  'peanuts':            { cal: 161, p: 7,   c: 5,   f: 14,  unit: '28g' },
  'cashews':            { cal: 157, p: 5,   c: 9,   f: 12,  unit: '28g' },
  'walnuts':            { cal: 185, p: 4,   c: 4,   f: 18,  unit: '28g' },
  'dates':              { cal: 20,  p: 0.2, c: 5.3, f: 0,   unit: 'piece' },
  'sugar':              { cal: 48,  p: 0,   c: 12,  f: 0,   unit: 'tsp' },
  'honey':              { cal: 64,  p: 0.1, c: 17,  f: 0,   unit: 'tbsp' },
  'jam':                { cal: 55,  p: 0.1, c: 14,  f: 0,   unit: 'tbsp' },
  'peanut butter':      { cal: 94,  p: 4,   c: 3,   f: 8,   unit: 'tbsp' },

  // ══════════════════════════════════════
  // 🌍 INTERNATIONAL FOODS
  // ══════════════════════════════════════
  'salad':              { cal: 80,  p: 3,   c: 10,  f: 3,   unit: 'bowl' },
  'caesar salad':       { cal: 180, p: 8,   c: 12,  f: 12,  unit: 'bowl' },
  'steak':              { cal: 271, p: 26,  c: 0,   f: 18,  unit: '100g' },
  'sushi':              { cal: 35,  p: 2,   c: 5,   f: 0.5, unit: 'piece' },
  'ramen':              { cal: 350, p: 14,  c: 50,  f: 10,  unit: 'bowl' },
  'tacos':              { cal: 210, p: 10,  c: 20,  f: 10,  unit: 'piece' },
  'burrito':            { cal: 380, p: 18,  c: 50,  f: 12,  unit: 'piece' },
  'pancake':            { cal: 90,  p: 2.5, c: 14,  f: 3,   unit: 'piece' },
  'waffle':             { cal: 220, p: 6,   c: 25,  f: 11,  unit: 'piece' },
  'croissant':          { cal: 231, p: 5,   c: 26,  f: 12,  unit: 'piece' },
  'bagel':              { cal: 270, p: 10,  c: 53,  f: 1.5, unit: 'piece' },
  'wrap':               { cal: 220, p: 8,   c: 30,  f: 7,   unit: 'piece' },
  'quinoa':             { cal: 120, p: 4.4, c: 22,  f: 2,   unit: '100g' },
  'granola':            { cal: 471, p: 10,  c: 64,  f: 20,  unit: '100g' },
  'muesli':             { cal: 360, p: 10,  c: 66,  f: 6,   unit: '100g' },
  'cereal':             { cal: 130, p: 3,   c: 28,  f: 1,   unit: 'cup' },

  // ══════════════════════════════════════
  // 🍛 MORE INDIAN CURRIES & GRAVIES
  // ══════════════════════════════════════
  'kadai chicken':      { cal: 270, p: 23,  c: 10,  f: 16,  unit: 'cup' },
  'chicken tikka':      { cal: 190, p: 28,  c: 3,   f: 7,   unit: '100g' },
  'chicken tandoori':   { cal: 220, p: 30,  c: 4,   f: 9,   unit: '100g' },
  'fish curry':         { cal: 190, p: 22,  c: 8,   f: 8,   unit: 'cup' },
  'prawn curry':        { cal: 180, p: 20,  c: 9,   f: 7,   unit: 'cup' },
  'egg curry':          { cal: 200, p: 12,  c: 10,  f: 13,  unit: 'cup' },
  'bhindi masala':      { cal: 120, p: 3,   c: 15,  f: 5,   unit: 'cup' },
  'baingan bharta':     { cal: 140, p: 3,   c: 18,  f: 6,   unit: 'cup' },
  'malai kofta':        { cal: 280, p: 8,   c: 22,  f: 18,  unit: 'cup' },
  'navratan korma':     { cal: 240, p: 7,   c: 20,  f: 15,  unit: 'cup' },
  'kadai paneer':       { cal: 290, p: 13,  c: 12,  f: 21,  unit: 'cup' },
  'shahi paneer':       { cal: 310, p: 13,  c: 15,  f: 23,  unit: 'cup' },
  'matar paneer':       { cal: 250, p: 12,  c: 14,  f: 17,  unit: 'cup' },
  'chana masala':       { cal: 160, p: 9,   c: 26,  f: 3,   unit: 'cup' },
  'baingan masala':     { cal: 130, p: 3,   c: 16,  f: 6,   unit: 'cup' },
  'vegetable curry':    { cal: 140, p: 4,   c: 18,  f: 6,   unit: 'cup' },
  'mixed veg':          { cal: 130, p: 4,   c: 17,  f: 5,   unit: 'cup' },

  // ══════════════════════════════════════
  // 🥘 STREET FOOD & CHAAT
  // ══════════════════════════════════════
  'vada pav':           { cal: 286, p: 7,   c: 40,  f: 11,  unit: 'piece' },
  'pani puri':          { cal: 30,  p: 1,   c: 6,   f: 0.5, unit: 'piece' },
  'bhel puri':          { cal: 180, p: 5,   c: 30,  f: 5,   unit: 'cup' },
  'sev puri':           { cal: 200, p: 4,   c: 32,  f: 6,   unit: 'serving' },
  'dahi puri':          { cal: 170, p: 4,   c: 26,  f: 5,   unit: 'serving' },
  'ragda pattice':      { cal: 250, p: 7,   c: 35,  f: 9,   unit: 'plate' },
  'chole bhature':      { cal: 550, p: 14,  c: 70,  f: 23,  unit: 'plate' },
  'masala puri':        { cal: 200, p: 5,   c: 28,  f: 8,   unit: 'serving' },
  'aloo tikki':         { cal: 150, p: 3,   c: 22,  f: 6,   unit: 'piece' },
  'papdi chaat':        { cal: 220, p: 5,   c: 32,  f: 8,   unit: 'serving' },
  'dahi bhalla':        { cal: 190, p: 6,   c: 28,  f: 6,   unit: 'serving' },
  'pakora':             { cal: 200, p: 4,   c: 22,  f: 10,  unit: '100g' },
  'paneer pakora':      { cal: 220, p: 8,   c: 18,  f: 13,  unit: '100g' },
  'bread pakora':       { cal: 180, p: 5,   c: 24,  f: 7,   unit: 'piece' },
  'cutlet':             { cal: 170, p: 5,   c: 23,  f: 6,   unit: 'piece' },

  // ══════════════════════════════════════
  // 🍚 MORE RICE VARIETIES
  // ══════════════════════════════════════
  'jeera rice':         { cal: 180, p: 3.5, c: 32,  f: 4,   unit: 'cup' },
  'ghee rice':          { cal: 220, p: 4,   c: 35,  f: 8,   unit: 'cup' },
  'kashmiri pulao':     { cal: 240, p: 5,   c: 38,  f: 7,   unit: 'cup' },
  'vegetable pulao':    { cal: 200, p: 5,   c: 35,  f: 5,   unit: 'cup' },
  'mutton biryani':     { cal: 340, p: 20,  c: 38,  f: 12,  unit: 'cup' },
  'hyderabadi biryani': { cal: 330, p: 19,  c: 39,  f: 11,  unit: 'cup' },
  'dum biryani':        { cal: 320, p: 18,  c: 38,  f: 10,  unit: 'cup' },
  'paneer biryani':     { cal: 280, p: 10,  c: 40,  f: 9,   unit: 'cup' },
  'egg biryani':        { cal: 290, p: 13,  c: 37,  f: 9,   unit: 'cup' },
  'prawn biryani':      { cal: 300, p: 17,  c: 38,  f: 9,   unit: 'cup' },

  // ══════════════════════════════════════
  // 🥤 HEALTHY DRINKS & SMOOTHIES
  // ══════════════════════════════════════
  'green smoothie':     { cal: 120, p: 3,   c: 23,  f: 2,   unit: 'glass' },
  'banana smoothie':    { cal: 180, p: 5,   c: 32,  f: 3,   unit: 'glass' },
  'berry smoothie':     { cal: 150, p: 4,   c: 28,  f: 2,   unit: 'glass' },
  'mango smoothie':     { cal: 200, p: 4,   c: 38,  f: 3,   unit: 'glass' },
  'almond milk':        { cal: 30,  p: 1,   c: 1,   f: 2.5, unit: '100ml' },
  'soy milk':           { cal: 54,  p: 3.3, c: 6,   f: 1.8, unit: '100ml' },
  'oat milk':           { cal: 47,  p: 1,   c: 8,   f: 1.5, unit: '100ml' },
  'green tea':          { cal: 2,   p: 0,   c: 0,   f: 0,   unit: 'cup' },
  'black tea':          { cal: 2,   p: 0,   c: 0.5, f: 0,   unit: 'cup' },
  'lemon water':        { cal: 6,   p: 0,   c: 2,   f: 0,   unit: 'glass' },
  'buttermilk':         { cal: 40,  p: 3,   c: 5,   f: 1,   unit: '200ml' },
  'jaljeera':           { cal: 45,  p: 1,   c: 10,  f: 0,   unit: 'glass' },
  'aam panna':          { cal: 90,  p: 0.5, c: 22,  f: 0.2, unit: 'glass' },
  'nimbu pani':         { cal: 50,  p: 0,   c: 13,  f: 0,   unit: 'glass' },
  'masala chai':        { cal: 60,  p: 2,   c: 8,   f: 2,   unit: 'cup' },

  // ══════════════════════════════════════
  // 🥗 SALADS & HEALTHY BOWLS
  // ══════════════════════════════════════
  'greek salad':        { cal: 150, p: 5,   c: 10,  f: 10,  unit: 'bowl' },
  'quinoa salad':       { cal: 180, p: 6,   c: 25,  f: 6,   unit: 'bowl' },
  'kale salad':         { cal: 120, p: 4,   c: 15,  f: 5,   unit: 'bowl' },
  'chickpea salad':     { cal: 160, p: 7,   c: 22,  f: 5,   unit: 'bowl' },
  'fruit salad':        { cal: 100, p: 1,   c: 24,  f: 0.5, unit: 'bowl' },
  'pasta salad':        { cal: 200, p: 6,   c: 30,  f: 6,   unit: 'bowl' },
  'tuna salad':         { cal: 180, p: 18,  c: 8,   f: 8,   unit: 'bowl' },
  'chicken salad':      { cal: 190, p: 20,  c: 10,  f: 8,   unit: 'bowl' },
  'buddha bowl':        { cal: 350, p: 12,  c: 48,  f: 12,  unit: 'bowl' },
  'poke bowl':          { cal: 380, p: 25,  c: 42,  f: 12,  unit: 'bowl' },
  'acai bowl':          { cal: 280, p: 5,   c: 48,  f: 8,   unit: 'bowl' },
  'grain bowl':         { cal: 320, p: 10,  c: 45,  f: 10,  unit: 'bowl' },

  // ══════════════════════════════════════
  // 🍞 BREADS & BAKERY
  // ══════════════════════════════════════
  'kulcha':             { cal: 180, p: 5,   c: 32,  f: 4,   unit: 'piece' },
  'garlic naan':        { cal: 290, p: 9,   c: 48,  f: 7,   unit: 'piece' },
  'butter naan':        { cal: 310, p: 9,   c: 48,  f: 9,   unit: 'piece' },
  'cheese naan':        { cal: 340, p: 13,  c: 50,  f: 10,  unit: 'piece' },
  'tandoori roti':      { cal: 80,  p: 3,   c: 15,  f: 1,   unit: 'piece' },
  'missi roti':         { cal: 100, p: 4,   c: 18,  f: 2,   unit: 'piece' },
  'bhakri':             { cal: 90,  p: 3,   c: 17,  f: 1,   unit: 'piece' },
  'thepla':             { cal: 110, p: 3,   c: 18,  f: 3,   unit: 'piece' },
  'methi paratha':      { cal: 200, p: 5,   c: 28,  f: 8,   unit: 'piece' },
  'gobi paratha':       { cal: 210, p: 5,   c: 30,  f: 8,   unit: 'piece' },
  'paneer paratha':     { cal: 240, p: 8,   c: 32,  f: 9,   unit: 'piece' },
  'mooli paratha':      { cal: 190, p: 4,   c: 27,  f: 7,   unit: 'piece' },
  'laccha paratha':     { cal: 220, p: 5,   c: 32,  f: 8,   unit: 'piece' },
  'pita bread':         { cal: 165, p: 5,   c: 33,  f: 1,   unit: 'piece' },
  'focaccia':           { cal: 210, p: 6,   c: 36,  f: 5,   unit: '100g' },
  'sourdough':          { cal: 120, p: 5,   c: 24,  f: 0.5, unit: 'slice' },
  'multigrain bread':   { cal: 85,  p: 4,   c: 14,  f: 1.5, unit: 'slice' },

  // ══════════════════════════════════════
  // 🍖 MORE PROTEINS & MEAT
  // ══════════════════════════════════════
  'lamb':               { cal: 294, p: 25,  c: 0,   f: 21,  unit: '100g' },
  'turkey':             { cal: 135, p: 25,  c: 0,   f: 3,   unit: '100g' },
  'duck':               { cal: 337, p: 19,  c: 0,   f: 28,  unit: '100g' },
  'pork':               { cal: 242, p: 27,  c: 0,   f: 14,  unit: '100g' },
  'bacon':              { cal: 541, p: 37,  c: 1,   f: 42,  unit: '100g' },
  'sausage':            { cal: 300, p: 13,  c: 3,   f: 27,  unit: '100g' },
  'ham':                { cal: 145, p: 21,  c: 1,   f: 6,   unit: '100g' },
  'crab':               { cal: 97,  p: 19,  c: 0,   f: 1,   unit: '100g' },
  'lobster':            { cal: 89,  p: 19,  c: 1,   f: 1,   unit: '100g' },
  'squid':              { cal: 92,  p: 16,  c: 3,   f: 1,   unit: '100g' },
  'octopus':            { cal: 82,  p: 15,  c: 2,   f: 1,   unit: '100g' },
  'mackerel':           { cal: 205, p: 19,  c: 0,   f: 14,  unit: '100g' },
  'sardine':            { cal: 208, p: 25,  c: 0,   f: 11,  unit: '100g' },
  'tilapia':            { cal: 128, p: 26,  c: 0,   f: 3,   unit: '100g' },
  'cod':                { cal: 82,  p: 18,  c: 0,   f: 1,   unit: '100g' },
  'hilsa':              { cal: 310, p: 22,  c: 0,   f: 25,  unit: '100g' },
  'pomfret':            { cal: 96,  p: 18,  c: 0,   f: 2,   unit: '100g' },
  'rohu':               { cal: 97,  p: 17,  c: 0,   f: 2,   unit: '100g' },
  'katla':              { cal: 150, p: 18,  c: 0,   f: 8,   unit: '100g' },

  // ══════════════════════════════════════
  // 🧈 CONDIMENTS & SPICES
  // ══════════════════════════════════════
  'mayonnaise':         { cal: 94,  p: 0.1, c: 0.1, f: 10,  unit: 'tbsp' },
  'ketchup':            { cal: 17,  p: 0.2, c: 4,   f: 0,   unit: 'tbsp' },
  'mustard':            { cal: 10,  p: 0.7, c: 1,   f: 0.6, unit: 'tbsp' },
  'soy sauce':          { cal: 8,   p: 1,   c: 1,   f: 0,   unit: 'tbsp' },
  'hot sauce':          { cal: 1,   p: 0,   c: 0,   f: 0,   unit: 'tsp' },
  'olive oil':          { cal: 119, p: 0,   c: 0,   f: 14,  unit: 'tbsp' },
  'coconut oil':        { cal: 121, p: 0,   c: 0,   f: 14,  unit: 'tbsp' },
  'vegetable oil':      { cal: 120, p: 0,   c: 0,   f: 14,  unit: 'tbsp' },
  'pickle':             { cal: 25,  p: 0.5, c: 4,   f: 1,   unit: 'tbsp' },
  'achaar':             { cal: 25,  p: 0.5, c: 4,   f: 1,   unit: 'tbsp' },

  // ══════════════════════════════════════
  // 🍰 MORE DESSERTS & SWEETS
  // ══════════════════════════════════════
  'rasgulla':           { cal: 150, p: 3,   c: 30,  f: 2,   unit: 'piece' },
  'sandesh':            { cal: 140, p: 4,   c: 25,  f: 3,   unit: 'piece' },
  'rasmalai':           { cal: 180, p: 5,   c: 28,  f: 6,   unit: 'piece' },
  'kaju katli':         { cal: 160, p: 3,   c: 22,  f: 7,   unit: 'piece' },
  'barfi':              { cal: 150, p: 3,   c: 23,  f: 6,   unit: 'piece' },
  'mysore pak':         { cal: 180, p: 3,   c: 25,  f: 8,   unit: 'piece' },
  'peda':               { cal: 140, p: 3,   c: 22,  f: 5,   unit: 'piece' },
  'jalebi':             { cal: 150, p: 1,   c: 30,  f: 4,   unit: '30g' },
  'imarti':             { cal: 160, p: 1,   c: 32,  f: 4,   unit: '30g' },
  'ghewar':             { cal: 200, p: 3,   c: 32,  f: 7,   unit: '50g' },
  'boondi ladoo':       { cal: 170, p: 3,   c: 26,  f: 7,   unit: 'piece' },
  'motichoor ladoo':    { cal: 180, p: 3,   c: 28,  f: 7,   unit: 'piece' },
  'besan ladoo':        { cal: 190, p: 4,   c: 26,  f: 8,   unit: 'piece' },
  'rava ladoo':         { cal: 170, p: 3,   c: 25,  f: 7,   unit: 'piece' },
  'coconut ladoo':      { cal: 160, p: 2,   c: 24,  f: 7,   unit: 'piece' },
  'kheer':              { cal: 165, p: 5,   c: 28,  f: 4,   unit: 'cup' },
  'shrikhand':          { cal: 190, p: 6,   c: 30,  f: 5,   unit: 'cup' },
  'kulfi':              { cal: 180, p: 4,   c: 26,  f: 7,   unit: 'piece' },
  'falooda':            { cal: 250, p: 6,   c: 42,  f: 7,   unit: 'glass' },
  'brownie':            { cal: 240, p: 3,   c: 30,  f: 12,  unit: 'piece' },
  'donut':              { cal: 250, p: 4,   c: 30,  f: 12,  unit: 'piece' },
  'muffin':             { cal: 220, p: 4,   c: 32,  f: 9,   unit: 'piece' },
  'cupcake':            { cal: 240, p: 3,   c: 35,  f: 10,  unit: 'piece' },
  'pudding':            { cal: 150, p: 4,   c: 26,  f: 4,   unit: 'cup' },
  'tiramisu':           { cal: 290, p: 6,   c: 28,  f: 17,  unit: 'slice' },
  'cheesecake':         { cal: 320, p: 6,   c: 26,  f: 22,  unit: 'slice' },
};

module.exports = FOOD_DB;
